### ISSUE TITLE
Wrong story opened under best sorting

### ISSUE THREAD

**Issue by bryan824** [ivanceras/hackernews-sauron#2]
Hi, I am learning to implement a router through this example cuz I cannot find a built-in one in sauron. When I open your online demo, it is StorySorting::Top by default. If I switch it to any other sorting and click on the link to open the story or user. It will show the corresponding one in Top sorting in terms of position.

Please let me know if there is a way to fix this. Thank you!

**Comment by ivanceras** [comment]
@bryan824 this is an issue with rearranged nodes with keys, where keyed item is being reused when the DOM changes. This hasn't been handled yet.

As for the case with hackernews example, Top sorting and best Sorting will most likely have story items that is common to both Sorting. 

There is a [test](https://github.com/ivanceras/mt-dom/blob/master/tests/rearranged_keyed_nodes.rs) that shows this case. It is currently annotated with `#[should_panic]`. The algorithm that handles all the diffing in keyed elements in found in [here](https://github.com/ivanceras/mt-dom/blob/master/src/diff/keyed_elements.rs)

I have been experimenting with a few algorithm to solve it but it messes with other cases, which would yields a lot of failing test.

**Comment by bryan824** [comment]
Thank you so much for the reply. I checked your second-to-last commit, it seems like adding "key" attribute back will fix the issue but I saw you added a bug label. Does it mean the future fix should not use "key" attribute?

**Comment by ivanceras** [comment]
This has now been fixed at version 0.49.0 of sauron with the use of new diffing algorithm for keyed elements in mt-dom 0.19.0 with this [commit](https://github.com/ivanceras/mt-dom/commit/941f462a71a4fa62c891c9c588893a7c181eb510)

**Comment by ivanceras** [comment]
Related fixed issue: https://github.com/ivanceras/sauron/issues/63
